# make-claude-md.ps1
#
# Bootstraps a target project for Claude Code and agent-agnostic harnesses:
#   1. Copies each skill from skills/ into .claude/commands/ as a Claude Code slash command
#   2. Generates CLAUDE.md at the project root with the coordination context
#   3. Writes .claude/settings.json with the GitHub MCP allowlist so parallel calls
#      don't stack at the permission prompt
#
# Usage (from skills repo root, targeting current dir):  .\make-claude-md.ps1
# Usage (from anywhere, targeting another project):      .\make-claude-md.ps1 C:\path\to\project

param(
    [string]$TargetDir = (Get-Location).Path
)

$SkillsDir    = Join-Path $PSScriptRoot "skills"
$CommandsDir  = Join-Path $TargetDir ".claude\commands"
$SettingsPath = Join-Path $TargetDir ".claude\settings.json"
$ClaudeMdPath = Join-Path $TargetDir "CLAUDE.md"

if (-not (Test-Path $SkillsDir)) {
    Write-Error "skills/ directory not found at: $SkillsDir"
    exit 1
}

$skills = Get-ChildItem -Path $SkillsDir -Filter "*.md" | Sort-Object Name

if ($skills.Count -eq 0) {
    Write-Error "No .md files found in $SkillsDir"
    exit 1
}

New-Item -ItemType Directory -Force -Path $CommandsDir | Out-Null

# --- 1. Install slash commands for Claude Code ---
foreach ($skill in $skills) {
    $dest = Join-Path $CommandsDir $skill.Name
    Copy-Item -Path $skill.FullName -Destination $dest -Force
    Write-Host "  command: .claude/commands/$($skill.Name)"
}

# --- 2. Write .claude/settings.json ---
# Pre-approves GitHub MCP tool calls so sequential issue/label/comment calls don't
# each trigger a permission prompt. If you already have a settings.json with other
# content, merge this "allow" list into it manually rather than overwriting.
if (Test-Path $SettingsPath) {
    Write-Host "  WARNING: .claude/settings.json already exists — not overwriting."
    Write-Host "  Add the following to its permissions.allow array manually:"
    Write-Host "    `"mcp__github__*`""
} else {
    $settingsJson = @'
{
  "permissions": {
    "allow": [
      "mcp__github__*"
    ]
  }
}
'@
    $settingsJson | Out-File -FilePath $SettingsPath -Encoding utf8 -NoNewline
    Write-Host "  settings: .claude/settings.json (mcp__github__* pre-approved)"
}

# --- 3. Generate CLAUDE.md ---
$commandList = ($skills | ForEach-Object { "- ``/$($_.BaseName)``" }) -join "`n"

$claudeMd = @"
# Hackathon Agent Coordination

> Auto-generated by make-claude-md. Re-run the bootstrap script to update.

Read ``AGENTS.md`` in full — it is the source of truth for the coordination protocol,
label states, claiming sequence, branch discipline, and handoff conventions.

## GitHub MCP — required for all GitHub operations

Use the **GitHub MCP** (``mcp__github__*``) for every GitHub operation in this project:
reading and writing issues, labels, assignees, comments, and pull requests.

Do **not** use ``gh``, ``curl``, the GitHub REST API directly, or any Bash command for
GitHub operations the MCP can handle. GitHub MCP calls are attributable and auditable;
ad-hoc CLI calls break the team's shared state.

Make MCP calls **sequentially, not in parallel**. Parallel calls stack at the permission
prompt and require a full retry cycle.

## Branch discipline

Never commit to ``main`` directly. Every issue gets its own branch.
Create the branch before writing any code. Open a PR to merge — that is the only
valid close-out path for completed work.

## Available slash commands

$commandList

"@

$claudeMd | Out-File -FilePath $ClaudeMdPath -Encoding utf8 -NoNewline

Write-Host ""
Write-Host "Bootstrap complete -> $TargetDir"
Write-Host "  CLAUDE.md written"
Write-Host "  $($skills.Count) slash command(s) installed in .claude/commands/"
Write-Host ""
Write-Host "For Claude Code: open the project — commands appear as /hackathon-* in the palette."
Write-Host "For other agents: paste AGENTS.md as a system prompt instead."
