# make-claude-md.ps1
#
# Bootstraps a target project for Claude Code and agent-agnostic harnesses:
#   1. Copies each skill from skills/ into .claude/commands/ as a Claude Code slash command
#   2. Generates CLAUDE.md at the project root with the coordination context
#
# Usage (from skills repo root, targeting current dir):  .\make-claude-md.ps1
# Usage (from anywhere, targeting another project):      .\make-claude-md.ps1 C:\path\to\project

param(
    [string]$TargetDir = (Get-Location).Path
)

$SkillsDir    = Join-Path $PSScriptRoot "skills"
$CommandsDir  = Join-Path $TargetDir ".claude\commands"
$ClaudeMdPath = Join-Path $TargetDir "CLAUDE.md"

if (-not (Test-Path $SkillsDir)) {
    Write-Error "skills/ directory not found at: $SkillsDir"
    exit 1
}

$skills = Get-ChildItem -Path $SkillsDir -Filter "*.md" | Sort-Object Name

if ($skills.Count -eq 0) {
    Write-Error "No .md files found in $SkillsDir"
    exit 1
}

# --- 1. Install slash commands for Claude Code ---
New-Item -ItemType Directory -Force -Path $CommandsDir | Out-Null

foreach ($skill in $skills) {
    $dest = Join-Path $CommandsDir $skill.Name
    Copy-Item -Path $skill.FullName -Destination $dest -Force
    Write-Host "  command: .claude/commands/$($skill.Name)"
}

# --- 2. Generate CLAUDE.md ---
$commandList = ($skills | ForEach-Object { "- ``/$($_.BaseName)``" }) -join "`n"

$claudeMd = @"
# Hackathon Agent Coordination

> Auto-generated by make-claude-md. Re-run the bootstrap script to update.

Read ``AGENTS.md`` in full — it is the source of truth for the coordination protocol,
label states, claiming sequence, and handoff conventions.

## GitHub MCP — required for all GitHub operations

Use the **GitHub MCP** (``mcp__github__*``) for every GitHub operation in this project:
reading and writing issues, labels, assignees, comments, and pull requests.

Do **not** use ``gh``, ``curl``, the GitHub REST API directly, or any Bash command for
GitHub operations the MCP can handle. GitHub MCP calls are attributable and auditable;
ad-hoc CLI calls break the team's shared state.

## Available slash commands

$commandList

"@

$claudeMd | Out-File -FilePath $ClaudeMdPath -Encoding utf8 -NoNewline

Write-Host ""
Write-Host "Bootstrap complete -> $TargetDir"
Write-Host "  CLAUDE.md written"
Write-Host "  $($skills.Count) slash command(s) installed in .claude/commands/"
Write-Host ""
Write-Host "For Claude Code: open the project and the commands appear as /hackathon-* in the palette."
Write-Host "For other agents: paste AGENTS.md as a system prompt instead."
