#!/usr/bin/env bash
#
# make-claude-md.sh
#
# Bootstraps a target project for Claude Code and agent-agnostic harnesses:
#   1. Copies each skill from skills/ into .claude/commands/ as a Claude Code slash command
#   2. Generates CLAUDE.md at the project root with the coordination context
#
# Usage (from skills repo root, targeting current dir):  ./make-claude-md.sh
# Usage (from anywhere, targeting another project):      ./make-claude-md.sh /path/to/project

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TARGET_DIR="${1:-$(pwd)}"
SKILLS_DIR="$SCRIPT_DIR/skills"
COMMANDS_DIR="$TARGET_DIR/.claude/commands"
CLAUDE_MD="$TARGET_DIR/CLAUDE.md"

if [ ! -d "$SKILLS_DIR" ]; then
  echo "Error: skills/ directory not found at: $SKILLS_DIR" >&2
  exit 1
fi

skills=("$SKILLS_DIR"/*.md)
if [ ${#skills[@]} -eq 0 ] || [ ! -f "${skills[0]}" ]; then
  echo "Error: no .md files found in $SKILLS_DIR" >&2
  exit 1
fi

# --- 1. Install slash commands for Claude Code ---
mkdir -p "$COMMANDS_DIR"

for skill in "${skills[@]}"; do
  name="$(basename "$skill")"
  cp "$skill" "$COMMANDS_DIR/$name"
  echo "  command: .claude/commands/$name"
done

# --- 2. Generate CLAUDE.md ---
command_list=""
for skill in "${skills[@]}"; do
  base="$(basename "$skill" .md)"
  command_list="${command_list}- \`/${base}\`
"
done

cat > "$CLAUDE_MD" <<EOF
# Hackathon Agent Coordination

> Auto-generated by make-claude-md. Re-run the bootstrap script to update.

Read \`AGENTS.md\` in full — it is the source of truth for the coordination protocol,
label states, claiming sequence, and handoff conventions.

## GitHub MCP — required for all GitHub operations

Use the **GitHub MCP** (\`mcp__github__*\`) for every GitHub operation in this project:
reading and writing issues, labels, assignees, comments, and pull requests.

Do **not** use \`gh\`, \`curl\`, the GitHub REST API directly, or any Bash command for
GitHub operations the MCP can handle. GitHub MCP calls are attributable and auditable;
ad-hoc CLI calls break the team's shared state.

## Available slash commands

${command_list}
EOF

echo ""
echo "Bootstrap complete -> $TARGET_DIR"
echo "  CLAUDE.md written"
echo "  ${#skills[@]} slash command(s) installed in .claude/commands/"
echo ""
echo "For Claude Code: open the project and the commands appear as /hackathon-* in the palette."
echo "For other agents: paste AGENTS.md as a system prompt instead."
